### ISSUE TITLE
Improve UI for month selection

### ISSUE THREAD

**Issue by marapredescu1** [RinneganOrg/React-Calendar#8]

**Comment by marapredescu1** [comment]
Expand to year selection in the future

**Comment by rexalex** [comment]
![Screenshot 2022-10-04 at 09 03 47](https://user-images.githubusercontent.com/7466122/193746057-346ffe02-6ead-41cf-afb5-8eb8ba354ee0.png)

**Comment by MihaelaCretu11** [comment]
Also implemented perpetuum calendar

**Comment by MihaelaCretu11** [comment]
Styling the option element from HTML, used for the month selection dropdown, is highly limited, because the box is rendered by the operating system. The only things that can be changed are the background color and the font size.

More information about this topic can be found here: 

1. https://stackoverflow.com/questions/7208786/how-to-style-the-option-of-an-html-select-element
2. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option

Here is a CodePen example to demonstrate that any other changes in the CSS file, beside the ones mentioned before, are not applied to the option element:
https://codepen.io/meems011/pen/oNdrqrj

**Comment by MihaelaCretu11** [comment]
Fixed
