### ISSUE TITLE
Use parent component functions for updates

### ISSUE THREAD

**Issue by marapredescu1** [RinneganOrg/React-Calendar#9]

**Comment by MihaelaCretu11** [comment]
will connect to firebase backend for persisting events (:

**Comment by MihaelaCretu11** [comment]
![Uploading 20221004_094608.jpg…]()

**Comment by MihaelaCretu11** [comment]
Blocked by #11 and #7
Current state:
- using dynamic events from parent component;
- create event by click on day cell;
- uses parent modal with own functions for submit/cancel.

Future state:
- based on view types, parent will give function to get events based on interval
- add functions from parent for update on drag and drop

**Comment by MihaelaCretu11** [comment]
Current state:

- using dynamic events from parent component;
- create event by click on day cell;
- uses parent modal with own functions for submit/cancel
- add functions from parent for update on drag and drop

Unblocked, because view types are handled by calendar, no need for parent to be aware, #11 will handle it.
